---

- name: Install Erlang
  include_tasks: "install-erlang-{{ ansible_os_family | lower }}.yml"

- name: Install elixir dependencies
  package:
    name: [ 'git', 'esl-erlang', 'elixir' ]
    state: present

- name: Create signaltower directory
  file:
    path: "{{ palava_signaltower_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Create signaltower log directory
  file:
    path: "{{ palava_signaltower_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Checkout Signltower
  git: 
    repo: 'https://github.com/palavatv/signaltower.git' 
    dest: /srv/signaltower
    version: "{{ palava_signaltower_version }}"

- name: Prepare Release
  shell: mix local.hex --force

- name: Install signaltower dependencies
  shell: "cd {{ palava_signaltower_install_dir }} && yes | mix deps.get"

- name: Set Release Type
  shell: "cd {{ palava_signaltower_install_dir }} && yes | MIX_ENV=prod mix release {{ palava_environment }}"

- name: Build Signaltower
  shell: "cd {{ palava_signaltower_install_dir }} && yes | mix deps.compile"

- name: Ensure palava_group exists
  group:
    name: "{{ palava_group }}"
    state: present

- name: Ensure palava_user exists
  user:
    name: "{{ palava_user }}"
    group: "{{ palava_group }}"

- name: Ensure signaltower ownership
  file:
    path: "{{ palava_signaltower_install_dir }}"
    owner: "{{ palava_user }}"
    group: "{{ palava_group }}"
    recurse: true

- name: Install Signaltower SystemD unit
  template:
    src: signaltower.service.j2
    dest: "/etc/systemd/system/signaltower-{{ palava_environment }}.service"

- name: Start Signaltower
  systemd:
    daemon_reload: "{{ palava_signaltower_autostart }}"
    enabled: "{{ palava_signaltower_autostart }}"
    name: "signaltower-{{ palava_environment }}.service"
