- name: Copy ngnix SSL config
  copy:
    src: ssl_extra.conf
    dest: /etc/nginx/ssl_extra
  notify: "restart nginx"

- name: Copy dhparam
  copy:
    src: dhparam
    dest: /etc/nginx/dhparam
  notify: "restart nginx"

- name: Copy ngnix log config
  copy:
    src: log_format.conf
    dest: /etc/nginx/log_format
  notify: "restart nginx"

- name: Register log_format
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    regexp: "^include log_format;"
    line: "include log_format;"
    insertafter: "^http {"
  notify: "restart nginx"

- name: Create empty default page
  template:
    src: nginx-default.html.j2
    dest: "/var/www/html/index.html"
  notify: restart nginx

- name: Remove nginx debian default page
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: Create default config
  template:
    src: nginx-default.conf.j2
    dest: "/etc/nginx/sites-available/default"
  notify: restart nginx

- name: Activate default config
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    owner: root
    group: root
    state: link
  notify: restart nginx

- name: Increase worker_connections to 20k
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "^\\s*worker_connections"
    line: "worker_connections 20000;"
  notify: restart nginx

- name: Remove server_tokens
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "^(\\s|#)*server_tokens"
    line: "server_tokens off;"
  notify: restart nginx

- include_tasks: palava.yml

- name: Validate nginx config
  command: nginx -t
  register: nginx_syntax_check
  ignore_errors: yes

- meta: flush_handlers
