---

palava_signaltower_install_dir: /srv/signaltower
palava_signaltower_log_dir: /var/log/signaltower
palava_signaltower_port: 4233
palava_signaltower_autostart: yes

# palava_signaltower_turn_secret: TURN_SECRET__IF_GIVEN_TURN_IS_ENABLED

palava_signaltower_version: master

palava_environment: production
palava_group: palava
palava_user: palava
