- name: Install common packages (monitoring)
  apt:
    name:
      - apt-transport-https
      - apache2-utils
      - fail2ban
      - nginx
      - unattended-upgrades
      - vim
    state: present

- name: Make sure some packages are not installed
  apt:
    name:
      - apache2
      - cups
      - telnet
    state: absent
