---

# common networking definitions
quad_zero_route: "0.0.0.0/0"
TCP_protocol: "6"
SSH_port: "22"

vcn_name: "myalwaysfreetestvcn"
vcn_cidr_block: "10.0.0.0/16"
vcn_dns_label: "alwaysfreevcn"

ig_name: "myalwaysfreeinternetgatewayformytestvcn"

route_table_name: "myalwaysfreeroutetable"
# route all internet access to our Internet Gateway
route_table_rules:
    - cidr_block: "{{ quad_zero_route }}"
      network_entity_id: "{{ ig_id }}"


subnet_cidr: "10.0.0.48/28"
subnet_name: "myalwaysfreetestsubnet"
subnet_dns_label: "myfreesubnet"

securitylist_name: "myalwaysfreesecuritylist"

# always free shape
instance_shape: "VM.Standard.E2.1.Micro"
instance_hostname: "myalwaysfreetestinstance"
instance_name: palava-monitoring-instance

# persistence
volume_name: palava-storevol
volume_size: 50G

#########################################
# Tenancy specific configuration
# *Note* - Override the following variables based on your tenancy
# or set a valid value for the corresponding environment variable
#########################################
instance_compartment: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"
# provide an "OL" image
# find OL image ocids per region here: https://docs.cloud.oracle.com/iaas/images/image/501c6e22-4dc6-4e99-b045-cae47aae343f/
# make sure the image you choose is compatible with Free Tier shape - VM.Standard.E2.1.Micro
instance_image: "{{ lookup('env', 'SAMPLE_IMAGE_OCID') }}"